service: frontend
variablesResolutionMode: 20210326
projectDir: ..

plugins:
  - serverless-s3-sync
  
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${env:TARGET_REGION}'}

custom: ${file(./custom.yml.js)}

resources:
  Resources: ${file(./sls-resources.yml.js)}
