service: sharing-service
variablesResolutionMode: 20210326
projectDir: ..

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-slic-watch-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, '${env:TARGET_REGION}'}
  tracing:
    apiGateway: true
    lambda: true
  environment:
    SLIC_STAGE: ${self:provider.stage}
    EMAIL_QUEUE_NAME: ${self:custom.emailQueueName}
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: 'execute-api:Invoke'
      Resource:
        - execute-api:/*/*/*
  logRetentionInDays: 7

custom:
  common: ${file(../slic-config.json)}
  webpack:
    keepOutputDirectory: true
  cloudFrontHostedZoneId: Z2FDTNDATAQYW2
  serverless-offline:
    httpPort: 4006
    lambdaPort: 4008
    websocketPort: 4007
    stage: local
    region: ${self:provider.region}
  emailQueueName: ${self:provider.stage}-email-queue
  prune:
    automatic: true
    number: 3
  slicWatch: ${self:custom.common.slicWatch}

functions: ${file(./sls-functions.yml)}

resources:
  Resources: ${file(./sls-resources.yml.js)}
